## Sections
## # required
## - each required entry must include reasoning for why the specific package is required.
##
## # prune
##
## # constraints
## - the constraints must be alphabetically sorted.
##
## # override
## - each override must include why the override is required.
## - the overrides must be alphabetically sorted.

required = [
  "k8s.io/gengo/types", # required for code generation from `pkg/apis`
  "k8s.io/code-generator/cmd/client-gen", # required for code generation from `pkg/apis`
]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/json-iterator/go"
    non-go = false
    go-tests = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
    go-tests = false
    unused-packages = false
  
  [[prune.project]]
    name = "k8s.io/gengo"
    non-go = false
    go-tests = false
    unused-packages = false

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/apparentlymart/go-cidr"
  version = "1.0.0"

[[constraint]]
  name = "github.com/google/renameio"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/ashcrow/osrelease"
  version = "1.0.0"

[[constraint]]
  name = "github.com/blang/semver"
  version = "v3.5.0"

[[constraint]]
  name = "github.com/coreos/container-linux-config-transpiler"
  version = "v0.9.0"

[[constraint]]
  name = "github.com/coreos/ignition"
  version = "0.26.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "v2.15.0"

[[constraint]]
  name = "github.com/openshift/api"
  branch = "master"

[[constraint]]
  name = "github.com/openshift/client-go"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/openshift/installer"

[[constraint]]
  name = "github.com/openshift/kubernetes-drain"
  revision = "c2e51be1758efa30d71a4d30dc4e2db86b70a4df"

[[constraint]]
  name = "github.com/openshift/library-go"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[[constraint]]
  name = "github.com/vincent-petithory/dataurl"
  revision = "9a301d65acbb728fcc3ace14f45f511a4cfeea9c"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.5"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.5"

[[constraint]]
  name = "k8s.io/kubelet"
  version = "kubernetes-1.12.5"

[[constraint]]
  name = "k8s.io/kubernetes"
  revision = "v1.12.5"

# TODO: include why the override is required
[[override]]
  name = "github.com/ajeddeloh/yaml"
  revision = "6b94386aeefd8c4b8470aee72bfca084c2f91da9"

# TODO: include why the override is required
[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.3"

# TODO: include why the override is required
[[override]]
  name = "k8s.io/gengo"
  revision = "fdcf9f9480fdd5bf2b3c3df9bf4ecd22b25b87e2"

# importing install-config is importing cluster-network-operator which adds sigs.k8s.io/controller-runtime as dependency.
# sigs.k8s.io/controller-runtime needs 1.12.3
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.12.5"

[[constraint]]
  branch = "release-1.12"
  name = "github.com/kubernetes-sigs/cri-o"

[[constraint]]
  revision = "0b67c788f2d234c9fecc3d372d93160869381166"
  name = "github.com/containers/storage"

[[override]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "29686dbc5559d93fb1ef402eeda3e35c38d75af4"

[[constraint]]
  name = "github.com/containers/image"
  revision = "1c10a197331c71709754037e2b7f7e7fc94c65cf"
