required = ["k8s.io/gengo/types", "k8s.io/code-generator/cmd/client-gen"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/json-iterator/go"
    non-go = false
    go-tests = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
    go-tests = false
    unused-packages = false
  
  [[prune.project]]
    name = "k8s.io/gengo"
    non-go = false
    go-tests = false
    unused-packages = false

[[constraint]]
  name = "github.com/coreos/ignition"
  version = "0.26.0"

[[constraint]]
  name = "github.com/coreos/container-linux-config-transpiler"
  version = "v0.9.0"


[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

[[override]]
  name = "github.com/ajeddeloh/yaml"
  revision = "6b94386aeefd8c4b8470aee72bfca084c2f91da9"

[[constraint]]
  name = "github.com/golang/glog"
revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/gengo"
  revision = "fdcf9f9480fdd5bf2b3c3df9bf4ecd22b25b87e2"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "v2.15.0"

[[constraint]]
  name = "github.com/blang/semver"
  version = "v3.5.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "v0.0.3"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v17"

[[constraint]]
  name = "github.com/wking/kubernetes-drain"
  revision = "b43d446bae992baacb39594d2d416b04ad78f307"

[[constraint]]
  name = "github.com/vincent-petithory/dataurl"
  revision = "9a301d65acbb728fcc3ace14f45f511a4cfeea9c"
