apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-pull-images-from-internal-registry
  namespace: {{.TargetNamespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-viewer
subjects:
- kind: ServiceAccount
  name: machine-config-daemon
  namespace: {{.TargetNamespace}}
  