apiVersion: "machineconfigurations.openshift.io/v1"
kind: "ControllerConfig"
spec:
  clusterDNSIP: "10.3.0.10"
  cloudProviderConfig: ""
  clusterName: "my-test-cluster"
  baseDomain: "installer.team.coreos.systems"
  etcdInitialCount: 3
  platform: "libvirt"
  etcdCAData: ZHVtbXkgZXRjZC1jYQo=
  rootCAData: ZHVtbXkgcm9vdC1jYQo=
  pullSecret:
    data: ZHVtbXkgZXRjZC1jYQo=
