# https://github.com/openshift/enhancements/blob/master/dev-guide/cluster-version-operator/dev/object-deletion.md
apiVersion: batch/v1
kind: CronJob
metadata:
  name: machine-config-nodes-crd-cleanup
  namespace: openshift-machine-config-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: Default
    release.openshift.io/delete: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: machine-config-operator
  namespace: openshift-machine-config-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    release.openshift.io/feature-set: Default
    release.openshift.io/delete: "true"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: machine-config-operator
  namespace: openshift-machine-config-operator
  labels:
    k8s-app: machine-config-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/feature-set: Default
    release.openshift.io/delete: "true"
