apiVersion: v1
kind: Service
metadata:
  name: machine-config-controller
  namespace: openshift-machine-config-operator
  labels:
    k8s-app: machine-config-controller
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    service.beta.openshift.io/serving-cert-secret-name: mcc-proxy-tls
spec:
  type: ClusterIP
  selector:
    k8s-app: machine-config-controller
  ports:
  - name: metrics
    port: 9001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: machine-config-daemon
  namespace: openshift-machine-config-operator
  labels:
    k8s-app: machine-config-daemon
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    service.beta.openshift.io/serving-cert-secret-name: proxy-tls
spec:
  type: ClusterIP
  selector:
    k8s-app: machine-config-daemon
  ports:
  - name: metrics
    port: 9001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: machine-config-server
  namespace: openshift-machine-config-operator
  labels:
    k8s-app: machine-config-server
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  type: ClusterIP
  selector:
    k8s-app: machine-config-server
  ports:
  - name: https
    port: 22623
    targetPort: 22623
    protocol: TCP
  - name: http
    port: 22624
    targetPort: 22624
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kube-rbac-proxy-crio
  namespace: openshift-machine-config-operator
  labels:
    k8s-app: kube-rbac-proxy-crio
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  type: ClusterIP
  selector:
    k8s-app: kube-rbac-proxy-crio
  ports:
  - name: metrics
    port: 9637
    targetPort: 9637
    protocol: TCP
