apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-config-osimageurl
  namespace: openshift-machine-config-operator
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
data:
  releaseVersion: 0.0.1-snapshot
  # The OS payload used for 4.10 and below; more information in
  # https://github.com/openshift/machine-config-operator/blob/master/docs/OSUpgrades.md
  # (The original issue was  https://github.com/openshift/machine-config-operator/issues/183 )
  osImageURL: "registry.svc.ci.openshift.org/openshift:machine-os-content"
