apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-config-operator-images
  namespace: openshift-machine-config-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
data:
  images.json: >
    {
      "releaseVersion": "0.0.1-snapshot",
      "machineConfigOperator": "registry.svc.ci.openshift.org/openshift:machine-config-operator",
      "etcd": "registry.svc.ci.openshift.org/openshift:etcd",
      "infraImage": "registry.svc.ci.openshift.org/openshift:pod",
      "kubeClientAgentImage": "registry.svc.ci.openshift.org/openshift:kube-client-agent",
      "clusterEtcdOperatorImage": "",
      "keepalivedImage": "registry.svc.ci.openshift.org/openshift:keepalived-ipfailover",
      "corednsImage": "registry.svc.ci.openshift.org/openshift:coredns",
      "mdnsPublisherImage": "registry.svc.ci.openshift.org/openshift:mdns-publisher",
      "haproxyImage": "registry.svc.ci.openshift.org/openshift:haproxy-router",
      "baremetalRuntimeCfgImage": "registry.svc.ci.openshift.org/openshift:baremetal-runtimecfg",
      "oauthProxy": "registry.svc.ci.openshift.org/openshift:oauth-proxy"
    }
