apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: machine-config
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
  relatedObjects:
    - group: ""
      name: openshift-machine-config-operator
      resource: namespaces
    - group: machineconfiguration.openshift.io
      resource: machineconfigpools
    - group: machineconfiguration.openshift.io
      resource: controllerconfigs
    - group: machineconfiguration.openshift.io
      resource: machineconfigs
    - group: machineconfiguration.openshift.io
      resource: kubeletconfigs
    - group: machineconfiguration.openshift.io
      resource: containerruntimeconfigs
    - group: ""
      resource: nodes
