filesystem: "root"
mode: 0644
path: "/etc/kubernetes/static-pod-resources/mdns/config.hcl.tmpl"
contents:
  inline: |
    {{ if .Infra.Status -}}
    {{ if .Infra.Status.PlatformStatus -}}
    {{ if .Infra.Status.PlatformStatus.VSphere -}}
    {{ if .Infra.Status.PlatformStatus.VSphere.APIServerInternalIP -}}
    bind_address = "{{`{{ .NonVirtualIP }}`}}"
    collision_avoidance = "hostname"

    service {
        name = "{{`{{ .Cluster.Name }}`}} Etcd"
        host_name = "{{`{{ .EtcdShortHostname }}`}}.local."
        type = "_etcd-server-ssl._tcp"
        domain = "local."
        port = 2380
        ttl = 3200
    }

    service {
        name = "{{`{{ .Cluster.Name }}`}} Workstation"
        host_name = "{{`{{ .ShortHostname }}`}}.local."
        type = "_workstation._tcp"
        domain = "local."
        port = 42424
        ttl = 3200
    }

    service {
        name = "{{`{{ .Cluster.Name }}`}} EtcdWorkstation"
        host_name = "{{`{{ .EtcdShortHostname }}`}}.local."
        type = "_workstation._tcp"
        domain = "local."
        port = 42424
        ttl = 300
    }
    {{ end -}}
    {{ end -}}
    {{ end -}}
    {{ end -}}
