apiVersion: machineconfiguration.openshift.io/v1
kind: ControllerConfig
metadata:
  name: machine-config-controller
  namespace: {{.TargetNamespace}}
spec:
  clusterDNSIP: {{.ControllerConfig.ClusterDNSIP}}
  cloudProviderConfig: {{.ControllerConfig.CloudProviderConfig}}
  clusterName: {{.ControllerConfig.ClusterName}}
  platform: {{.ControllerConfig.Platform}}
  baseDomain: {{.ControllerConfig.BaseDomain}}
  etcdCAData: {{.ControllerConfig.EtcdCAData | toString | b64enc}}
  rootCAData: {{.ControllerConfig.RootCAData | toString | b64enc}}
