apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "machineconfigpool-osimagestream-reference-validation-binding"
spec:
  policyName: "machineconfigpool-osimagestream-reference-validation"
  validationActions: [Deny]
  paramRef:
    name: "cluster"
    parameterNotFoundAction: "Deny"
