apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-push-images-to-internal-registry
  namespace: {{.TargetNamespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-editor
subjects:
- kind: ServiceAccount
  name: machine-config-controller
  namespace: {{.TargetNamespace}}