filesystem: "root"
mode: 0644
path: "/etc/systemd/system/machine-config-daemon-host.service.d/10-default-env.conf"
contents:
  inline: |
    {{if .Proxy -}}
    [Service]
    {{if .Proxy.HTTPProxy -}}
    Environment=HTTP_PROXY="{{.Proxy.HTTPProxy}}"
    {{end -}}
    {{if .Proxy.HTTPSProxy -}}
    Environment=HTTPS_PROXY="{{.Proxy.HTTPSProxy}}"
    {{end -}}
    {{if .Proxy.NoProxy -}}
    Environment=NO_PROXY="{{.Proxy.NoProxy}}"
    {{end -}}
    {{end -}}
