name: ovs-configuration.service
enabled: {{if eq .NetworkType "OVNKubernetes"}}true{{else}}false{{end}}
contents: |
  [Unit]
  Description=Configures OVS with proper host networking configuration
  # This service is used to move a physical NIC into OVS and reconfigure OVS to use the host IP
  Requires=openvswitch.service
  Wants=NetworkManager-wait-online.service
  After=NetworkManager-wait-online.service openvswitch.service node-valid-hostname.service
  Before=network-online.target kubelet.service crio.service

  [Service]
  # Need oneshot to delay kubelet
  Type=oneshot
  ExecStart=/usr/local/bin/configure-ovs.sh
  StandardOutput=journal+console
  StandardError=journal+console

  [Install]
  WantedBy=network-online.target
